language: bash
services: docker

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - image='hello-world'

script:
  - ./update.sh
  - test -z "$(git status --porcelain '*/hello' '*/nanoserver/hello.txt')"
  - travis_retry travis_retry travis_retry docker build -t "$image" hello-world
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
